### ISSUE TITLE
osiam-registration-module 0.17.1 incompatible with OSIAM 1.3.2

### ISSUE THREAD

**Issue by mirabilos** [osiam/server#269]
This is more of an FYI issue, so others don’t search for this too:

osiam-registration-module contains a line in WEB-INF/classes/sql/registration_extension.sql that says:

SELECT pg_catalog.setval('hibernate_sequence', 10, false);

This sequence apparently no longer exists in OSIAM upstream. I removed the offending line, and the database import succeeded. Please advice whether this is the correct fix, and consider releasing a new version of the osiam-registration-module.

**Comment by tkrille** [comment]
Hi @mirabilos,

and thanks for the hint. `osiam-registration-module` and any pre-1.0 version are not officially supported anymore. In fact, `osiam-registration-module` is deprecated since over one and a half year and doesn't exist as an artifact anymore. So this will be closed as "won't fix".

Thanks again for your help, much appreciated.

**Comment by tkrille** [comment]
accepted as bug and re-opened.

**Comment by tkrille** [comment]
@mirabilos Fixed with e9d2e9f.

Release has been built and is available here: https://maven-repo.evolvis.org/releases/org/osiam/osiam-registration-module/0.17.2/osiam-registration-module-0.17.2.war
